---
version: "3.8"
services:
  prometheus:
    image: docker.io/prom/prometheus:v2.48.1
    ports:
      - 127.0.1.1:9090:9090
    volumes:
      - ./monitoring/prom/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: docker.io/grafana/grafana:10.0.10
    ports:
      - 127.0.1.1:3000:3000
    volumes:
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources/
      - ./monitoring/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/general.yaml
      - ./monitoring/grafana/dashboards:/dashboards
